"""rename reservation2

Revision ID: a81884b5e221
Revises: 3644de47f4b3
Create Date: 2024-05-11 12:01:12.988719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a81884b5e221'
down_revision: Union[str, None] = '3644de47f4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(), nullable=False),
    sa.Column('count_of_people', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reservations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hotel_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('count_of_people', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reservation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='reservations_pkey')
    )
    op.drop_table('reservation')
    # ### end Alembic commands ###
