"""reservations table

Revision ID: 2660eee2b391
Revises: 0b6239d5270d
Create Date: 2024-05-11 09:49:42.608655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2660eee2b391'
down_revision: Union[str, None] = '0b6239d5270d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(), nullable=False),
    sa.Column('count_of_people', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    # ### end Alembic commands ###
