"""change reservation columns

Revision ID: abb1e6eb82d3
Revises: a81884b5e221
Create Date: 2024-05-12 08:34:36.134294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb1e6eb82d3'
down_revision: Union[str, None] = 'a81884b5e221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('reservation', sa.Column('second_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'second_name')
    op.drop_column('reservation', 'first_name')
    # ### end Alembic commands ###
